version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update git submodules
          command: 'git submodule update --init --recursive'
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
