jobs:
  checkout-update:
    executor:
      name: node/default
      tag: '10.4'
      
    steps:
      - checkout
      - node/with-cache:
          steps:     
          - run:
              name: Update git submodules
              command: 'git submodule update --init --recursive'
    
  docker-build:
    executor: docker/docker
      
    steps:
      - docker/check
      - docker/build
      
orbs:
  node: circleci/node@1.1
  docker: circleci/docker@1.0.0

version: 2.1
