jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node:
          steps:     
          - run:
              name: Update git submodules
              command: 'git submodule update --init --recursive'
          - run:
              name: Docker build
              command: docker build .

orbs:
  node: circleci/node@1.1
version: 2.1
