version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
    
    
jobs:

  deploy:
    <<: *defaults 
    steps:
      deploy:
        - checkout
        
workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy
