version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
          
      - run:
          name: Update git submodules
          command: 'git submodule update --init --recursive'
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose    
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
